### ISSUE TITLE
About Pascal-Part-116 dataset

### ISSUE THREAD

**Issue by NWPUliuxx** [OpenRobotLab/OV_PARTS#11]
Hello.

Thank you for sharing the nice work!

I have a question about ADE20K-Part234 dataset.

Follow the operations in Data Preparation,the dataset directory should be as follows:
Datasets/
├─Pascal-Part-116/
│ ├─train_16shot.json
│ ├─images/
│ │ ├─train/
│ │ └─val/
│ ├─annotations_detectron2_obj/
│ │ ├─train/
│ │ └─val/
│ └─annotations_detectron2_part/
│   ├─train/
│   └─val/
But I downloaded the Pascal Part-116 dataset, and the val directory is not available in annotations_detectron2_part

Could you give me the information?

Thank you.

**Comment by nhw649** [comment]
+1

**Comment by kellyiss** [comment]
We have released the validation set. Please click the download link again to access it.
