### ISSUE TITLE
Question regarding `Pred-Obj Setting`

### ISSUE THREAD

**Issue by JihoChoi** [OpenRobotLab/OV_PARTS#14]
Thank you for sharing your nice research.
While studying the code you made available, we encountered a few questions and would appreciate your guidance.

1)
Where can I find the code for the `Pred-Obj Setting` mentioned in the paper?
The Pred-obj setting experiment does not seem to work in the currently released code.
Even after setting the `ORACLE` field to `False` in the config file [1], I couldn't locate the section that branches to the correct data mapper [2] or modifies the computation by excluding the background [3] and ground truth. Could you please clarify?

2)
The paper mentions a 1.2% performance drop for the `Pred-Obj Setting` compared to the `Oracle-Obj Setting`.
How can I reproduce this result? As there is no provided code, our modified code shows a more significant difference from the `Oracle-Obj Setting` due to factors like the uncategory (background).

For reference:
* (1) Oracle-Obj Setting: The ground-truth mask and class of objects are assumed to be known.
* (2) Pred-Obj Setting: The ground-truth mask and class of objects are not provided.

Thank you for your assistance.

[1] https://github.com/OpenRobotLab/OV_PARTS/blob/main/configs/zero_shot/clipseg_voc.yaml#L1
[2] https://github.com/OpenRobotLab/OV_PARTS/blob/main/train_net.py#L112-L119
[3] https://github.com/OpenRobotLab/OV_PARTS/blob/main/baselines/clipseg.py#L84

**Comment by kellyiss** [comment]
We use a simple way to run the Pred-Obj Setting by changing the gt object annotations path to a predicted one. 
You can use any semantic segmentation models (as powerful as you can find) to run the object segmentation  and save the results in the same format with the ground truth files. As this setting is more related to the object model, any object models can be used to improve the performance.

**Comment by JihoChoi** [comment]
Thank you very much for your prompt and kind response.

To clarify, the results of the `Pred-Obj` setting in the paper were derived using the object masks predicted by an **additional object segmentation model** and replacing the Ground Truth (GT) object label, correct?
If my understanding is correct, could you please provide more details about which model (or a list of models) where used to predict object segmentation as reported in the paper?

Thank you once again for your assistance.
