### ISSUE TITLE
Missing json annotations in pascalpart inference

### ISSUE THREAD

**Issue by ProvenceStar** [OpenRobotLab/OV_PARTS#2]
Hi，i appreciate your work. But i noticed that when i tried to run inference on pascal-part116, the error occurs:
"FileNotFoundError: [Errno 2] No such file or directory: 'datasets/PascalPart116/annotations_detectron2_part/val_obj_label_count.json'"
I wonder how can i get the json annotation file to reproduce your result, thanks!

**Comment by kellyiss** [comment]
Sorry about the missing script for generating the json files. 
I have uploaded it in baselines/data/datasets/mask_cls_collect.py
Please check the README.md to see how to generate.

**Comment by ProvenceStar** [comment]
Thanks a lot!
