### ISSUE TITLE
Can you kindly explain what is the difference between oracle-cls and pred-cls?

### ISSUE THREAD

**Issue by yxchng** [OpenRobotLab/OV_PARTS#3]
![Screenshot from 2023-12-07 22-29-26](https://github.com/OpenRobotLab/OV_PARTS/assets/10518587/eb17e83c-38fd-4f30-b113-3cb2f520e93d)

The description here is not very clear to me. For example, regarding oracle-cls, if ground-truth masks and class are assumed to be known, what is there to be predicted?

**Comment by kellyiss** [comment]
For oracle-obj, we use ground-truth masks and classes of objects, you only need to predict the corresponding parts of this oracle object. For pred-obj, you need to predict both the object and part correctly.

**Comment by JihoChoi** [comment]
Thank you for your answer.
The currently released code seems to be based on `oracle-obj`.
How do I check the `pred-obj` settings?

**Comment by JihoChoi** [comment]
Thank you for your answer.
The currently released **evaluation code** seems to be based on `oracle-obj`.
How do I check the `pred-obj` settings?
