### ISSUE TITLE
Environment setup not consistent with detectron2

### ISSUE THREAD

**Issue by Gorluxor** [OpenRobotLab/OV_PARTS#4]
The instructions for the env setup include https://github.com/OpenRobotLab/OV_PARTS/blob/4a2a6ec0c44ac6a8b934a49fdf0c8568736f7d27/requirements.txt#L9
which comes with CUDA 11.6 or CUDA 11.7. which does not have a pre-compiled wheel as far as https://detectron2.readthedocs.io/en/latest/tutorials/install.html official wheels are concerned. 

Can you clarify which version of CUDA you used and the steps you used for the environment to run your code?  

Thanks for the great work!

**Comment by kellyiss** [comment]
Yes, I find that somehow I use pytorch 1.13.1+cu117 with CUDA 11.3. So I change it to 1.12.1 which also works well.
You can just install torch==1.12.1.
I'll update the requirements.txt. Thanks!
